# -*- coding: utf-8 -*-
"""scraping_spotify_playstore

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i6SjIxTHYyRTIgtt71G3WbqaWFxH91Qb
"""

# Import Library
!pip install Sastrawi
!pip install google-play-scraper

# Standard library imports
import datetime as dt  # Manipulasi data waktu dan tanggal
import re  # Modul untuk bekerja dengan ekspresi reguler
import string  # Berisi konstanta string, seperti tanda baca

# Third-party imports
import matplotlib.pyplot as plt  # Matplotlib untuk visualisasi data
import nltk  # Pustaka NLTK (Natural Language Toolkit)
import numpy as np  # NumPy untuk komputasi numerik
import pandas as pd  # Pandas untuk manipulasi dan analisis data
import seaborn as sns  # Seaborn untuk visualisasi data statistik
from google_play_scraper import Sort, app, reviews, reviews_all  # Mengakses info aplikasi Play Store
from nltk.corpus import stopwords  # Daftar kata-kata berhenti dalam teks
from nltk.tokenize import word_tokenize  # Tokenisasi teks
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory  # Stemming bahasa Indonesia
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory  # Menghapus kata berhenti bahasa Indonesia
from wordcloud import WordCloud  # Membuat visualisasi berbentuk awan kata (word cloud)


# Konfigurasi Pandas & NumPy
pd.options.mode.chained_assignment = None  # Menonaktifkan peringatan chaining
seed = 0
np.random.seed(seed)  # Mengatur seed untuk reproduktibilitas

# Mengunduh dataset NLTK yang diperlukan
nltk.download('punkt')
nltk.download('stopwords')

print("Melakukan proses scraping data...")
result, continuation_token = reviews(
    'com.spotify.music',
    lang='id',
    country='id',
    sort=Sort.MOST_RELEVANT,
    count=100000  # Jumlah data yang diambil
)

# Data ulasannya ada di variabel 'result'
scrapreview = result

# Membuat DataFrame dari hasil scrapreview
app_reviews_df = pd.DataFrame(scrapreview)

# Menghitung jumlah baris dan kolom dalam DataFrame
jumlah_ulasan, jumlah_kolom = app_reviews_df.shape
print(f"Jumlah ulasan: {jumlah_ulasan}, Jumlah kolom: {jumlah_kolom}")

# Menampilkan 5 baris pertama
print("Menampilkan 5 data pertama:")
print(app_reviews_df.head())

# Menyimpan ulasan ke dalam file CSV (satu kali menggunakan pandas to_csv)
print("Menyimpan ulasan ke ulasan_sp.csv...")
app_reviews_df.to_csv('ulasan_sp.csv', index=False)
print("Selesai.")